service: scraper

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  stage: ${opt:stage, "dev"}

functions:
  test-scraper:
    memorySize: 256
    timeout: 60
    image:
      uri: 654654376195.dkr.ecr.us-west-2.amazonaws.com/scraper:latest
      command:
        - dist/index.handler
